fixup! Merge branch 'master' of github.com:eclipse/che-machine-exec into release-fixup

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -10,6 +10,10 @@ on:
       noCommit:
         description: 'If true, will not commit the version bump changes'
         default: ''
+      forceRecreateTags:
+        description: If true, tags will be recreated. Use with caution
+        required: false
+        default: 'false'
 jobs:
   build:
     name: Create Release
@@ -19,6 +23,23 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
+      - name: Check existing tags
+        run: |
+          set +e
+          RECREATE_TAGS=${{ github.event.inputs.forceRecreateTags }}
+          VERSION=${{ github.event.inputs.checkoutExistingTag }}
+          EXISTING_TAG=$(git ls-remote --exit-code origin refs/tags/${version})
+          if [[ -n ${EXISTING_TAG} ]]; then
+            if [[ ${RECREATE_TAGS} == "true" ]]; then
+              echo "[INFO] Removing tag for ${version} version. New tag will be recreated during release."
+              git push origin :${{ github.event.inputs.version}}
+            else
+              echo "[ERROR] Cannot proceed with release - tag ${EXISTING_TAG} already exists."
+              exit 1
+            fi
+          else
+            echo "[INFO] No existing tags detected for ${version}"
+          fi
       - name: Login to docker.io
         uses: docker/login-action@v1
         with:
